### ISSUE TITLE
LingLibre windows (standalone) error

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#10]
Hi, I saw your post back on reddit and decided to check how the LingLibre is working and whether it's a good alternative to LWT.
This is what shows up when trying to launch it on Windows.

![image](https://user-images.githubusercontent.com/15344931/118399995-3181a000-b636-11eb-96b3-a4cdbc8c2990.png)

I'll try the built-in Django server instead, but I couldn't get the standalone executable to work.

Thanks for the attention.

**Comment by gustavklopp** [comment]
Thanks for the report! I've uploaded a new updated release.
