### ISSUE TITLE
Error importing lwt database.

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#11]
Idk if I was supposed to do this, so I'm just _ASSUMING_ the database structures are shared between both lwt and linglibre.

Anyways, here's the database backup: 
[lwt-backup-2021-05-19-03-41-34.sql.gz](https://github.com/gustavklopp/LingL/files/6527268/lwt-backup-2021-05-19-03-41-34.sql.gz)

And the page displayed once it importation fails (HTML page)
[DeserializationError at _backuprestore_.zip](https://github.com/gustavklopp/LingL/files/6527270/DeserializationError.at._backuprestore_.zip)

**Comment by gustavklopp** [comment]
I see where the problem is. I will work on a fix.

**Comment by ezxpro** [comment]
Hey, just one thing. 

I noticed now that when I tried to restore this backup and sent you this log, I used the regular "restore database" rather than the "import from lwt" (I didn't notice this second option, my bad) and posted the resulting error here. I checked the old version and this _DeserializationError at backuprestore.zip_ happens only when trying to use the regular restore function. When trying to use the "import from lwt" function it fails too, but produces another error.

I don't know if you noticed I made this confusion, but anyways, my bad. 

On the new release btw (the one from yesterday), I still can't import it. I may send you the logs if you want, but I think you can reproduce it using the backup I originally sent when I opened the issue.

**Comment by gustavklopp** [comment]
Ok, it should work with the new release.

> Hey, just one thing.
> 
> I noticed now that when I tried to restore this backup and sent you this log, I used the regular "restore database" rather than the "import from lwt" (I didn't notice this second option, my bad) and posted the resulting error here. I checked the old version and this _DeserializationError at backuprestore.zip_ happens only when trying to use the regular restore function. When trying to use the "import from lwt" function it fails too, but produces another error.

I will create an alert to prevent uploading the wrong files, I think it will be better.

**Comment by ezxpro** [comment]
Importing the database worked just fine now, following the latest release. I'm closing this issue.
