### ISSUE TITLE
When creating a language, how should I fill mandatory fields?

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#13]
I'm having an issue with the mandatory fields when creating a language. See: 

![image](https://user-images.githubusercontent.com/15344931/119260062-72823300-bba7-11eb-8760-d76801c3cee3.png)
I don't use anki. So even though there's a documentation for it available in the internet, it is not interesting for me to go there and learn what these templates are all about if I'm not using them.

The fields pertaining the EOL character thing are also mandatory.

I am opening this issue because it's not quite clear to me how should I fill these fields in order to create a new language.

**Comment by gustavklopp** [comment]
Hi ezxpro! Thanks a lot for the report.
I've made a video to better explain how it works. Hope it helps!
https://tube.tchncs.de/videos/watch/7e6f7661-46b3-494d-8426-d9438bebf871

**Comment by ezxpro** [comment]
Well, the problem seems to be, when I select the language from the dropdown, nothing happens. 
I tried in both Chrome and Firefox

![image](https://user-images.githubusercontent.com/15344931/119282054-857c1e00-bc0e-11eb-831f-e0081c9b4adb.png)

**Comment by gustavklopp** [comment]
Try with the new release https://github.com/gustavklopp/LingL/releases

**Comment by ezxpro** [comment]
When creating a language, the issue persists. I select a language template from the drop down, nothing happens.

Also, how should I go about updating the _standalone_ version, because as it is, it seems that if I just extract the files to the same folder, the database will be erased. Here is a screenshot of the users table right before extracting the new version:
![image](https://user-images.githubusercontent.com/15344931/119343345-b1c68780-bc6c-11eb-8782-387763613cec.png)
 
 And here right after extraction:
 
![image](https://user-images.githubusercontent.com/15344931/119343595-09fd8980-bc6d-11eb-815f-e8ab404bed81.png)

So I'm assuming that if I am to upgrade I am supposed to take a database backup before, right? If that's the case, I think it may be necessary to point that out on the Readme or the release page.

**Comment by gustavklopp** [comment]
It should work now with the new release.

> So I'm assuming that if I am to upgrade I am supposed to take a database backup before, right? If that's the case, I think it may be necessary to point that out on the Readme or the release page.

Yes, it's better to do a backup. I've detail how to do it on the homepage: https://github.com/gustavklopp/LingL#3-upgrading

**Comment by ezxpro** [comment]
Alright, I am testing the latest release, the language dropdown finally works. I'll close this issue.

And thanks for the instructions in the home page, that's nice 😊
