### ISSUE TITLE
TemplateSyntaxError at /text_detail/ when trying to create a new text.

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#14]
On the latest release (the one from yesterday), when I select any of the predefined language templates (French, Portuguese, German, any of them) and click "New Text" (as seen below)
![image](https://user-images.githubusercontent.com/15344931/119347341-c8bba880-bc71-11eb-99b7-481299476073.png)

I get an error, that can be seen on the screenshot or the zipped HTML file below
![image](https://user-images.githubusercontent.com/15344931/119347477-f7398380-bc71-11eb-869e-07af4943a1f9.png)

[TemplateSyntaxError at _text_detail_.zip](https://github.com/gustavklopp/LingL/files/6532272/TemplateSyntaxError.at._text_detail_.zip)

Also, if we're to keep testing this and reporting the errors, I'd suggest you to come up with some versioning scheme so that we can refer to the specific releases, bc as it is I already see myself coming back and forth from different  versions to see if a specific issue has been resolved, and referring to them requires a specific versioning template for reference.

**Comment by gustavklopp** [comment]
It should be fixed with the new release from today.

> Also, if we're to keep testing this and reporting the errors, I'd suggest you to come up with some versioning scheme so that we can refer to the specific releases, bc as it is I already see myself coming back and forth from different versions to see if a specific issue has been resolved, and referring to them requires a specific versioning template for reference.

Good idea! Now I've put the LingLibre version on the top right of the homepage. 
(It's also in the appversion.txt file (at the root of the released folder) if the program isn't launching at all)

**Comment by ezxpro** [comment]
I'm also closing this issue, I can create texts normally on the newest version.
