### ISSUE TITLE
FileNotFoundError at /language_detail/ when trying to edit a language

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#15]
See
![image](https://user-images.githubusercontent.com/15344931/119347761-59928400-bc72-11eb-9a97-458793df03e5.png)

Resulting error:

![image](https://user-images.githubusercontent.com/15344931/119347837-729b3500-bc72-11eb-909c-c995a35f656b.png)
[FileNotFoundError at _language_detail_.zip](https://github.com/gustavklopp/LingL/files/6532312/FileNotFoundError.at._language_detail_.zip)

Btw, do you think it's necessary to attach the html page showing the error, or you suggest a different way of sending the logs from an error?

**Comment by gustavklopp** [comment]
Thanks a lot for the report! I've released a new version. It should work.

> Btw, do you think it's necessary to attach the html page showing the error, or you suggest a different way of sending the logs from an error?

If the log is too long, you can paste it here for example: https://pastebin.com/

**Comment by ezxpro** [comment]
Yeah, this has also been fixed. Thanks for the pastebin tip.
