### ISSUE TITLE
Visual bug on the dictionary frame 

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#22]
It doesn't seem to be happening with wordreference though.
https://imgur.com/a/F4OxuXm
By the way, regardless of the dictionary, when I click a term it loads the dictionary but doesn't search any word.

**Comment by gustavklopp** [comment]
Thanks. I've fixed the API for dict.cc

**Comment by gustavklopp** [comment]
Is it fixed? Can I close it?

By the way, I've uploaded a video to show how it's working! Hope you enjoy it: https://tube.tchncs.de/videos/watch/4a017c2e-72a4-4e19-b024-6fe66e3aa407

**Comment by ezxpro** [comment]
Yeah, it is fixed now, but when importing from LWT, I have to manually add the `<WORD>` thing in the dictionary URL, otherwise I get that same visual glitch.

Once that is done, it works properly though.

**Comment by ezxpro** [comment]
I see there's now a message mentioning the how to set the dictionary after restore. Very handy. I'm closing this issue now.
