### ISSUE TITLE
"My Terms" link doesn't show any words.

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#23]
https://imgur.com/a/KiIrbmj

Tried to check all terms, nothing came up.

**Comment by ezxpro** [comment]
Just saw the same happens in the "export to Anki" section. 

https://imgur.com/a/NPVgG1G

I started testing Anki last week, would be nice if I could export the terms to practice later.

**Comment by gustavklopp** [comment]
Thanks. It's fixed in today's release.

**Comment by ezxpro** [comment]
Tried testing the latest version, got this error when restoring the database (not from LWT, but from LingL): https://pastebin.com/An4szSXe

**Comment by gustavklopp** [comment]
> Tried testing the latest version, got this error when restoring the database (not from LWT, but from LingL): https://pastebin.com/An4szSXe

It seems to be another issue: I've created a new one here: https://github.com/gustavklopp/LingL/issues/24

**Comment by gustavklopp** [comment]
Hi @ezxpro  I couldn't reproduce it with my own backup files since they are working for me.
Would it be possible to upload your yaml.gz backup file? (Put it on the issue I've opened at https://github.com/gustavklopp/LingL/issues/24)

**Comment by ezxpro** [comment]
Appears to be working now, I'll close this one.
