### ISSUE TITLE
Problem when restoring backup

### ISSUE THREAD

**Issue by gustavklopp** [gustavklopp/LingL#24]
Tried testing the latest version, got this error when restoring the database (not from LWT, but from LingL): https://pastebin.com/An4szSXe

**Comment by ezxpro** [comment]
[lwt-backup-2021-06-05-04-14-53.sql.gz](https://github.com/gustavklopp/LingL/files/6643124/lwt-backup-2021-06-05-04-14-53.sql.gz)
Here it is, the backup

**Comment by ezxpro** [comment]
[lingl_backup_2021-06-10_23h19.yaml.gz](https://github.com/gustavklopp/LingL/files/6643126/lingl_backup_2021-06-10_23h19.yaml.gz)

**Comment by gustavklopp** [comment]
I don't know why, your save was corrupted. I've "cleaned" it here: 
[lingl_backup_2021-06-13_08h16.yaml.gz](https://github.com/gustavklopp/LingL/files/6643525/lingl_backup_2021-06-13_08h16.yaml.gz)

**Comment by ezxpro** [comment]
I just made a test, seems lingl is creating broken backups. I tried making another backup using the latest version. When restoring I get the same error from above.
[lingl_backup_2021-06-13_13h10.yaml.gz](https://github.com/gustavklopp/LingL/files/6643917/lingl_backup_2021-06-13_13h10.yaml.gz)

**Comment by ezxpro** [comment]
> I don't know why, your save was corrupted. I've "cleaned" it here:
> [lingl_backup_2021-06-13_08h16.yaml.gz](https://github.com/gustavklopp/LingL/files/6643525/lingl_backup_2021-06-13_08h16.yaml.gz)


Also, same issue persists here with this file too.

**Comment by gustavklopp** [comment]
Yes, there was a bug with the German special characters on WIndows. It's fixed now. Thanks for reporting!
You can try the new release (use this backup also:
[lingl_backup_2021-06-13_15h38.yaml.gz](https://github.com/gustavklopp/LingL/files/6644300/lingl_backup_2021-06-13_15h38.yaml.gz)

**Comment by ezxpro** [comment]
Yes, it works just fine now. But only if I import either LWT or a LingL backup. 

Using the backup you posted above and the following LWT backup.
[lwt-backup-2021-06-13-22-53-11.sql.gz](https://github.com/gustavklopp/LingL/files/6644682/lwt-backup-2021-06-13-22-53-11.sql.gz)

1. If I restore LingL then LWT I get this https://pastebin.com/x0PUjK2j
2. If I restore LWT then LingL I get this https://pastebin.com/7BEdcSmQ
3. It's always the second restoration that fails

**Comment by gustavklopp** [comment]
Ok, it should work now with today's release.

**Comment by ezxpro** [comment]
Worked fine now, you can close this if you want.
