### ISSUE TITLE
Export to Anki button is greyed out

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#25]
If I select a couple words and try to export them, the button doesn't work.
https://imgur.com/a/AuGZET3

**Comment by gustavklopp** [comment]
Ok, it should work now with today's release.
To create the "export template" for Anki, you can use one of the predefined languages as model since I've updated their template for them. (But you can create your own template of course)

**Comment by ezxpro** [comment]
Working fine now.
