### ISSUE TITLE
Does not work on MacOS Big sur

### ISSUE THREAD

**Issue by chengxicn** [gustavklopp/LingL#27]
MacOS Big sur 11.4

MacBook-Pro ~ % /Users/i/Downloads/exe.macosx-10.15-x86_64-3.8/LingLibre ; exit;
Traceback (most recent call last):
  File "/Users/lingl/.pyenv/versions/3.8.9/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 81, in run
  File "/Users/lingl/.pyenv/versions/3.8.9/lib/python3.8/site-packages/cx_Freeze/initscripts/Console.py", line 36, in run
  File "LingL_app.py", line 6, in <module>
  File "/Users/lingl/.pyenv/versions/3.8.9/lib/python3.8/tkinter/__init__.py", line 36, in <module>
ImportError: dlopen(/Users/i/Downloads/exe.macosx-10.15-x86_64-3.8/lib/_tkinter.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/tcl-tk/lib/libtcl8.6.dylib
  Referenced from: /Users/i/Downloads/exe.macosx-10.15-x86_64-3.8/lib/_tkinter.cpython-38-darwin.so
  Reason: image not found
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by gustavklopp** [comment]
Big-sur is not compatible with Catalina? Oh my! What a wonderful OS...
For hours I've tried to update my virtual machine to Big-sur to check this error but it's really loooong.

**Comment by gustavklopp** [comment]
Thanks for the report!
I've uploaded a new version today: https://github.com/gustavklopp/LingL/releases/tag/LATEST.mac
Let me know if it's not working.

**Comment by chengxicn** [comment]
Thank you!

ccc@MacBook-Pro / % /Applications/LingL-0.0.0.app 
zsh: permission denied: /Applications/LingL-0.0.0.app

ccc@MacBook-Pro / % ls -l /Applications/LingL-0.0.0.app 
total 0
drwxr-xr-x@ 6 ccc  admin  192 Jun 21 00:01 Contents

**Comment by gustavklopp** [comment]
What does double-clicking?

chmod +x?
sudo /Applications/LingL-0.0.0.app?

I've uploaded a new release (same name but with open permissions at https://github.com/gustavklopp/LingL/releases/tag/LATEST.mac), what does it do?

**Comment by chengxicn** [comment]
click LingL dmg and drag LingL-0.0.0.app into Application folder
1. double-clicking: icon flash and disappear 
2. chmod +x :
```
   ccc@MacBook-Pro / % chmod +x /Applications/LingL-0.0.0.app 
  ccc@MacBook-Pro / % ls -l  /Applications/LingL-0.0.0.app   
 total 0
 drwxr-xr-x@ 6 ccc  admin  192 Jun 21 00:01 Contents
 ccc@MacBook-Pro / % /Applications/LingL-0.0.0.app      
 zsh: permission denied: /Applications/LingL-0.0.0.app
```
3. sudo
```
ccc@MacBook-Pro / % sudo /Applications/LingL-0.0.0.app
Password:
sudo: /Applications/LingL-0.0.0.app: command not found
```


```
ccc@MacBook-Pro / % sudo /Applications/LingL-0.0.0.app/Contents/MacOS/LingLibre
Password:
Traceback (most recent call last):
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 81, in run
  File "/Users/lingl/.pyenv/versions/venv3810/lib/python3.8/site-packages/cx_Freeze/initscripts/Console.py", line 36, in run
  File "LingL_app.py", line 34, in <module>
  File "/Users/lingl/.pyenv/versions/3.8.10/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /usr/local/Cellar/tcl-tk/8.6.11_1/lib/tcl8.6 /Applications/LingL-0.0.0.app/Contents/lib/tcl8.6 /Applications/LingL-0.0.0.app/lib/tcl8.6 /Applications/LingL-0.0.0.app/Contents/library /Applications/LingL-0.0.0.app/library /Applications/LingL-0.0.0.app/tcl8.6.11/library /Applications/tcl8.6.11/library



This probably means that Tcl wasn't installed properly.
```

4. new LingL :  same

**Comment by gustavklopp** [comment]
Do:
```
brew install tcl-tk
```
and then launch LingL (by double-clicking)

**Comment by chengxicn** [comment]
Finally solved!Very appreciate
