### ISSUE TITLE
Language filter always filters out everything

### ISSUE THREAD

**Issue by m-cote** [gustavklopp/LingL#3]
On the text list page after checking any item in the language filter, the list becomes empty.
Before:
![2021-05-03_16-15_initial](https://user-images.githubusercontent.com/7547394/116880845-2b012a80-ac2b-11eb-89d3-ba2b53cb5420.png)
After clicking on language checkbox:
![2021-05-03_16-16_after](https://user-images.githubusercontent.com/7547394/116891348-43774200-ac37-11eb-8200-91093e32f134.png)
Expected to see a list of texts in chosen language:
![image](https://user-images.githubusercontent.com/7547394/116894005-3e67c200-ac3a-11eb-9d9f-976287fdc602.png)

As a user, I just need to be able to switch the target language. So it would suffice to have the text list always display texts in current target language.

**Comment by gustavklopp** [comment]
Maybe because you haven't chosen any "last time open" on the screenshot, so there will be no texts displayed?
But I've changed the behavior when opening LingL for the first time: no "last time open" is selected. It's less confusing.

**Comment by m-cote** [comment]
After fix to the initial state of the 'last time open' filter, language filter works as expected.

**Comment by gustavklopp** [comment]
I've found bugs when using it (due to the facts that the filters for tags disappear). Now it's working normally.
