### ISSUE TITLE
unknown locale: en_150

### ISSUE THREAD

**Issue by edoreld** [gustavklopp/LingL#31]
When I create an account, I get an error that prevents me from continuing.

I'm on Windows 10.

<html><body>
<h1>ValueError
       at /</h1>
  <pre class="exception_value">unknown locale: en_150</pre>
  
``` 
Request Method: | GET
-- | --
http://127.0.0.1:8000/
3.2
ValueError
unknown locale: en_150
C:\Users\bureau\AppData\Local\Programs\Python\Python38\lib\locale.py, line 499, in _parse_localename
C:\Users\Edoreld\Downloads\exe.win-amd64-3.8\LingLibre.exe
3.8.9
['C:\\Users\\Edoreld\\Downloads\\exe.win-amd64-3.8',  'C:\\Users\\Edoreld\\Downloads\\exe.win-amd64-3.8\\lib\\library.zip',  'C:\\Users\\Edoreld\\Downloads\\exe.win-amd64-3.8\\lib']
Fri, 09 Jul 2021 17:00:10 +0000

<!--EndFragment-->
</body>
</html>
```

![image](https://user-images.githubusercontent.com/973854/125112990-446d9980-e0e8-11eb-94f1-4f142d6f41c2.png)

**Comment by gustavklopp** [comment]
On windows, what are your settings concerning the 'Country or Region' and 'Regional format' in 'Set Regional Format' ?
(in the quick search type 'set Regional format'.)

**Comment by edoreld** [comment]
![image](https://user-images.githubusercontent.com/973854/125192138-81e83900-e246-11eb-97c4-54505ff128e8.png)

**Comment by gustavklopp** [comment]
Thanks for reporting!
Try today release.

**Comment by edoreld** [comment]
Seems to work, but now I have [another issue](https://github.com/gustavklopp/LingL/issues/33)

**Comment by gustavklopp** [comment]
Ok, thank you!
