### ISSUE TITLE
local variable 'savedlanguage' referenced before assignment

### ISSUE THREAD

**Issue by edoreld** [gustavklopp/LingL#33]
Steps to reproduce:

1. Clone repo @ 54983b9617c4ea628e4f015d05f395db173ebd9e
2. Follow the instructions in the README under **2.2. Use the built-in server inside Django:**
3. Login 
4. Choose German as language
5. Click on save

Stacktrace:
```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/language_detail/?new=0

Django Version: 3.2.3
Python Version: 3.9.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django.contrib.humanize',
 'lwt',
 'tags_input',
 'mathfilters',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'crispy_forms']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\Users\Edoreld\Documents\LingL\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Edoreld\Documents\LingL\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Edoreld\Documents\LingL\venv\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Edoreld\Documents\LingL\lwt\views\language.py", line 117, in language_detail
    setter_settings_cookie_and_db('currentlang_id', savedlanguage.id, request)

Exception Type: UnboundLocalError at /language_detail/
Exception Value: local variable 'savedlanguage' referenced before assignment

```

**Comment by gustavklopp** [comment]
And no error when using the stand-alone program?

I couldn't reproduce this.
I have created a User with : I know: 'English´. I learn: 'Italian'.
Then go to http://127.0.0.1:8000.
Create a new language: in the drop-down list, choose German. The fields are filled automatically, then save.

or maybe can you post the entire page of the bug report on pastebin.com?

**Comment by edoreld** [comment]
How can I try the standalone program? The latest release I can see is from May and I'm not sure how to generate the executable myself.

**Comment by gustavklopp** [comment]
> How can I try the standalone program? The latest release I can see is from May 

The latest binaries are here: https://github.com/gustavklopp/LingL/releases
There's a bug in Github which displays the wrong date. But if the name of the program is "windows LingLibre 2021.07.11" it means it has been created on July 11th 2021.

>and I'm not sure how to generate the executable myself.

It's only useful for developers since the binaries are faster to use. But if you really want to build it yourself follow the instructions here:
https://github.com/gustavklopp/LingL#5-developers

**Comment by edoreld** [comment]
It's working with the latest release. Thanks!
