### ISSUE TITLE
Importing long texts fails in unhelpful manner

### ISSUE THREAD

**Issue by edoreld** [gustavklopp/LingL#35]
I tried importing a long text and it crashed with the error "Request body exceeded settings.DATA_UPLOAD_MAX_MEMORY_SIZE". As a user, how am I supposed to know what the limit is when importing texts?

It would be helpful if there was a feature like on [LWT](https://github.com/edoreld/learning-with-texts) where you can import a long text, and it splits the long text automatically into smaller texts.

**Comment by gustavklopp** [comment]
Can you upload (or give a link) to the file that you have tried to import please?

**Comment by edoreld** [comment]
You may find the text here: https://www.gutenberg.org/cache/epub/56064/pg56064.txt

**Comment by gustavklopp** [comment]
Thanks! I've removed the default limit (which was 2.5Mb initially).

**Comment by gustavklopp** [comment]
Ok, I'm closing this since it has been solved apparently.
