### ISSUE TITLE
"Help" Button goes to homepage

### ISSUE THREAD

**Issue by joshuaoco** [gustavklopp/LingL#37]
**Paste the Debug page**
Sorry, where is this debug page located? I'd reccomend making this very obvious to help users write good reports :)

Hiya,

The "help" button on the Home menu, and associated "help" links appear to go just to the front page.

Is the help page currently unimplemented?

https://user-images.githubusercontent.com/31520645/127814012-4c01ecf6-a5ca-44d3-a861-6e8c31c944aa.mp4

**Comment by gustavklopp** [comment]
Which version are you using? (standalone app, Docker version or Django internal server) 
and on which platform? (macOS, Linux or Windows)

**Comment by joshuaoco** [comment]
Sorry Gustav,

I'm using the Docker version, on Linux.

Joshua

**Comment by gustavklopp** [comment]
That's strange, it's working normally with me (Docker on linux)! Can somebody confirm this bug?

**Comment by joshuaoco** [comment]
I've just pulled the latest version and tried again and it appears to be fixed, closing.
