### ISSUE TITLE
Backup/Restore/Empty Database should be allowed only to superusers

### ISSUE THREAD

**Issue by m-cote** [gustavklopp/LingL#5]
Regular users are presented with link `Backup/Restore/Empty Database`, can follow this link and make use of functions like backup, restore from backup, install demo database, empty database. These functions should not be allowed for non superuser because they affect all users. The link `Backup/Restore/Empty Database` should only be displayed for superusers, all requests GET /backuprestore/ and POST /backuprestore/ should be forbidden for non superusers.

**Comment by gustavklopp** [comment]
I've changed the administration tasks in the last commit so that they impact only the user in question.

**Comment by m-cote** [comment]
It seems it does work. I suggest to change descriptions according to the new functionality. https://github.com/gustavklopp/LingL/pull/7

**Comment by gustavklopp** [comment]
Good idea! I've merged it.
