### ISSUE TITLE
Why language from "Origin lang code" field is being added to 'My Languages' during sign up?

### ISSUE THREAD

**Issue by m-cote** [gustavklopp/LingL#8]
After recent changes the drop-down list 'Origin lang code' on the sign up page became very limited. Previously new user could choose any language under the sun, but now only a few select languages are available.
![image](https://user-images.githubusercontent.com/7547394/117360047-f9a18c80-aec0-11eb-98ff-bf4be026eff3.png)

During the sign up process the language from 'Origin lang code' field gets added to the 'My languages' list.
![image](https://user-images.githubusercontent.com/7547394/117360649-b85dac80-aec1-11eb-9547-c23019cdfdca.png)

Maybe it would be more appropriate to ask for both languages during sign up and add only the target language?
![image](https://user-images.githubusercontent.com/7547394/117361721-12ab3d00-aec3-11eb-9753-1c64aaaa4c68.png)

**Comment by gustavklopp** [comment]
The change on the Sign up form is a very good idea, thanks! I've implemented that (and corrected also the language display bug).
By the way, I've changed the initialization process for the database for the first time (see readme): it's 

```
./manage.py loaddata    initial_fixture_USER.yaml
./manage.py loaddata    initial_fixture_LANGUAGES.yaml
```

**Comment by m-cote** [comment]
It's cool to see this feature coming together. Not sure whether it's related but I have an issue with saving language after editing. After I edit the language and click 'save' I get the message 'Languages with this Name and Owner already exists.' and I stay on the same page, the changes are not saved.
![image](https://user-images.githubusercontent.com/7547394/117714556-c8d29780-b1df-11eb-8887-f4b4f9a7aa00.png)
If I change the Name of the language, the changes are going to be saved as usual.

**Comment by gustavklopp** [comment]
Sorry for the bug... I've fixed it.
