### ISSUE TITLE
On 'New Text' page 'language' drop-down list contains languages owned by 'lingl'

### ISSUE THREAD

**Issue by m-cote** [gustavklopp/LingL#9]
![image](https://user-images.githubusercontent.com/7547394/117365339-d4644c80-aec7-11eb-9fd9-00813bb892ae.png)

1. Make sure there are some languages in 'lingl' account
2. Log in as a regular user
3. Click New Text
As a result, in the drop-down list 'Language' there are languages that actually defined in the 'lingl' account (alongside with languages defined in the current user account). If the user saves a text with any language from the 'lingl' account, then he is not going to be able to see it in the texts list because 'Language' filter always filters texts by languages defined in the user account.
It is expected to see, in the drop-down list 'Language', only languages that are defined in the current user account.

**Comment by gustavklopp** [comment]
You should delete the previous database. Follow the Readme then to repopulate the database:
```
python manage.py migrate
python manage.py loaddata ./lwt/fixtures/initial_fixture.yaml
```
Now, there are the admin account `lingl` doesn´t own any languages. the account `lingl` should be used only for Django administrative tasks.

**Comment by gustavklopp** [comment]
Thanks for reporting! fix at the same time than https://github.com/gustavklopp/LingL/issues/8
